# Generated by Django 2.2.1 on 2019-05-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='username',
            new_name='user',
        ),
    ]
